server:
  port: 9210

springdoc:
 api-docs:
   path: /v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
 swagger-ui:
   path: /swagger-ui.html
     
spring:
  boot:
    admin:
      client:
         url: http://172.16.15.192:9000 #Admin portal url.
         instance:
           name: report-service
           service-base-url: http://172.16.15.191:9200 #This is current application url. 
  application:
    name: report-service
  datasource:
    url: jdbc:sqlserver://172.16.15.120:1433;databaseName=OPS360UAT;encrypt=true;trustServerCertificate=true;
    username: appuser
    password: hitachi@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

        
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
 
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
          
jwt:
  auth:
    converter:
      resource-id: ${keycloak.resource}
      principle-attribute: preferred_username  
      
  
keycloak:
  domain: 172.16.15.192:9102
  realm: HPY
  resource: ops360
  issuer-uri: http://${keycloak.domain}
  adminClientSecret: 3Asf42GnEqOfatIQZULao5764AoYNnLY
  auth-server-url: http://${keycloak.domain}
  adminClientId: ${keycloak.resource}
  urls:
    auth: http://${keycloak.domain}
    tokenURL: http://${keycloak.domain}/realms/${keycloak.realm}/protocol/openid-connect/token
  ssl-required: external
  use-resource-role-mappings: true
        
eureka:
  instance:
    prerfer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://172.16.15.192:9101/eureka
  
logging:
  level:
    com.hpy: INFO
     
synergy:
  base-url: https://ops360dev.hitachi-payments.com/synergy/HitachiAPI_Integration/api
  username: OPS360API
  password: Cogent@123
  
app:
  cross-origin:
    allow: https://ops360uat.hitachi-payments.com
ops360:
  assets:
    base-path: /usr/ops360/Assets/
    base-url: https://ops360uat.hitachi-payments.com/path/
  dashboard:
    max-atm-list-count: 5

