Server:
  port: 9206

spring:
  boot:
    admin:
      client:
        url: http://localhost:9000 #Admin portal url.
        instance:
          name: synergyService
          service-base-url: http://localhost:9206 #This is current application url.
  application:
    name: synergy-service         
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always          
          
logging:
  level:
    com.hpy: debug
  file:
    name: D:/var/synergy_logs/application.log 

synergy:
  base-url: https://ops360uat.hitachi-payments.com/ops/synergy/HitachiAPI_IntegrationUAT/api
  username: OPS360API
  password: Cogent@123
  

jwt:
  auth:
    converter:
      resource-id: ${keycloak.resource}
      principle-attribute: preferred_username  

keycloak:
  domain: 127.0.0.1:8080
  realm: HPY
  resource: ops-360
  issuer-uri: http://${keycloak.domain}
  adminClientSecret: Q8Gz70vzjzFmMMoL8EFBKx3z9Pz7v3Qv
  auth-server-url: http://${keycloak.domain}
  adminClientId: ${keycloak.resource}
  urls:
    auth: http://${keycloak.domain}
    tokenURL: http://${keycloak.domain}/realms/${keycloak.realm}/protocol/openid-connect/token
  ssl-required: external
  use-resource-role-mappings: true  

app:
  maxFileSize: 2097152
  cross-origin:
    allow: https://ops360uat.hitachi-payments.com
  
eureka:
  instance:
    prerfer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:9101/eureka