Server:
  port: 9206

spring: 
  boot:
    admin:
      client:
        url: http://172.16.15.192:9000 #Admin portal url.
        instance:
          name: Synergy Service
          service-base-url: http://172.16.15.191:9206 #This is current application url.
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


synergy:
  base-url: https://crm360.hitachi-payments.com/HitachiAPI_Integration/api
  username: OPS360API
  password: Cogent@123

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  

jwt:
  auth:
    converter:
      resource-id: ${keycloak.resource}
      principle-attribute: preferred_username  


keycloak:
  domain: 172.16.15.192:9102
  realm: HPY
  resource: ops360
  issuer-uri: http://${keycloak.domain}
  adminClientSecret: 3Asf42GnEqOfatIQZULao5764AoYNnLY
  auth-server-url: http://${keycloak.domain}
  adminClientId: ${keycloak.resource}
  urls:
    auth: http://${keycloak.domain}
    tokenURL: http://${keycloak.domain}/realms/${keycloak.realm}/protocol/openid-connect/token
  ssl-required: external
  use-resource-role-mappings: true  

app:
  maxFileSize: 2097152
  cross-origin:
    allow: https://ops360uat.hitachi-payments.com
  
eureka:
  instance:
    prerfer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://172.16.15.192:9101/eureka