server:
  port: 9104

springdoc:
 api-docs:
   path: /v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
 swagger-ui:
   path: /swagger-ui/index.html

app:
  cross-origin:
    allow: https://ops360uat.hitachi-payments.com   
  
spring:
  application:
    name: user-access-management 
  datasource:
    url: jdbc:sqlserver://172.16.15.120:1433;databaseName=OPS360;encrypt=true;trustServerCertificate=true;
    username: appuser
    password: hitachi@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: false 
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs      

  mail:
    host: smtp-cluster27.immenzaces.com
    username: hitachi@hitachi-payments.com
    password: "1d6%cf98b61d4"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

response:
  columns: "username, firstName, lastName, email, groupName, mobile, statusCode, status"
  
jwt:
  auth:
    converter:
      resource-id: ${keycloak.resource}
      principle-attribute: preferred_username  
  
  
keycloak:
  domain: localhost:8080
  realm: HPY
  resource: ops360
  issuer-uri: http://${keycloak.domain}
  adminClientSecret: KjjqdKprBQpL8a24bsWSkI6zGqtYIQLg
  auth-server-url: http://${keycloak.domain}
  adminClientId: ${keycloak.resource}
  urls:
    auth: http://${keycloak.domain}
    tokenURL: http://${keycloak.domain}/realms/${keycloak.realm}/protocol/openid-connect/token
  ssl-required: external
  use-resource-role-mappings: true
    
eureka:
  instance:
    prerfer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:9101/eureka
      
basePath: D:\\my-data\\uam-service\\




#logging:
#  level:
#    ROOT: trace