server:
  port: 9191

spring:
  application:
    name: keycloak-base
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: ${keycloak.resource}
      principle-attribute: preferred_username  
  
  
keycloak:
  domain: 127.0.0.1:8080
#  domain: 172.16.15.192:9102
#  domain: ops360dev.hitachi-payments.com:9102
  realm: HPY
  resource: ops-360
  issuer-uri: http://${keycloak.domain}
  adminClientSecret: Q8Gz70vzjzFmMMoL8EFBKx3z9Pz7v3Qv
  auth-server-url: http://${keycloak.domain}
  adminClientId: ${keycloak.resource}
  urls:
    auth: http://${keycloak.domain}
    tokenURL: http://${keycloak.domain}/realms/${keycloak.realm}/protocol/openid-connect/token

  ssl-required: external
  use-resource-role-mappings: true 
  
eureka:
  instance:
    prerfer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
#      defaultZone: http://172.16.15.192:9101/eureka
      defaultZone: http://localhost:9101/eureka