
Server:
  port: 9201
  
spring:
  boot:
    admin:
      client:
         url: http://172.16.15.192:9000 #Admin portal url.
         instance:
           name: Location Service
           service-base-url: http://172.16.15.192:9201
  application:
    name: location-service
  datasource:
    url: jdbc:sqlserver://172.16.15.132:1433;databaseName=OPS360UAT;encrypt=true;trustServerCertificate=true;
    username: appuser
    password: hitachi@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

osrm:
  api:
    url: http://172.16.15.191:9109/route/v1/driving/

jwt:
  auth:
    converter:
      resource-id: ${keycloak.resource}
      principle-attribute: preferred_username 
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      
keycloak:
  domain: 127.0.0.1:8080
#  domain: 172.16.15.192:9102
#  domain: ops360dev.hitachi-payments.com:9102
  realm: HPY
  resource: ops-360
  issuer-uri: http://${keycloak.domain}
  adminClientSecret: z3eKogRSMg1PQo4SLJ4etTHdpD95jmYa
  auth-server-url: http://${keycloak.domain}
  adminClientId: ${keycloak.resource}
  urls:
    auth: http://${keycloak.domain}
    tokenURL: http://${keycloak.domain}/realms/${keycloak.realm}/protocol/openid-connect/token
  ssl-required: external
  use-resource-role-mappings: true

eureka:
  instance:
    prerfer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
#      defaultZone: http://172.16.15.192:9101/eureka
      defaultZone: http://127.0.0.1:9101/eureka
#      defaultZone: http://172.16.15.192:9101/eureka