Server:
  port: 9401

spring:
  boot:
    admin:
      client:
         url: http://172.16.15.192:9000 #Admin portal url.
         instance:
           name: Telemetry Service
           service-base-url: http://172.16.15.191:9202 #This is current application url.
  application:
    name: Telemetry-Service
  datasource:
    url: jdbc:sqlserver://172.16.15.120:1433;databaseName=OPS360UAT;encrypt=true;trustServerCertificate=true;
    username: appuser
    password: hitachi@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


synergy:
  base-url: https://ops360dev.hitachi-payments.com/synergy/HitachiAPI_Integration/api
  username: OPS360API
  password: Cogent@123

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  

jwt:
  auth:
    converter:
      resource-id: ${keycloak.resource}
      principle-attribute: preferred_username  


keycloak:
  domain: 172.16.15.192:9102
  realm: HPY
  resource: ops360
  issuer-uri: http://${keycloak.domain}
  adminClientSecret: 3Asf42GnEqOfatIQZULao5764AoYNnLY
  auth-server-url: http://${keycloak.domain}
  adminClientId: ${keycloak.resource}
  urls:
    auth: http://${keycloak.domain}
    tokenURL: http://${keycloak.domain}/realms/${keycloak.realm}/protocol/openid-connect/token
  ssl-required: external
  use-resource-role-mappings: true  

app:
  documentUploadDirectory: D:\\documentDirectory
  maxFileSize: 2097152
  cross-origin:
    allow: https://ops360uat.hitachi-payments.com
  
eureka:
  instance:
    prerfer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://172.16.15.192:9101/eureka

ops360:
  ticketing:
    max-atm-list-count: 5
    atm-batch-size: 50
    
knowlarity-service:
       url: http://172.16.15.192:9207/knowlarity
uam-service:
       url:  http://172.16.15.192:9100/user-service

dashboard-service:
       url: http://172.16.15.192:9200/Cm_portalATMDetails	

synergy-service:
       url: http://172.16.15.192:9206/synergy
oauth-service:
       url: http://172.16.15.192:9103/oauth