#
spring:
  profiles:
    active: dev

#Server:
#  port: 9400
#
#spring:
#  application:
#    name: ticketing
#  datasource:
#    url: jdbc:sqlserver://172.16.15.120:1433;databaseName=OPS360;encrypt=true;trustServerCertificate=true;
#    username: appuser
#    password: hitachi@123
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  
# 
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    open-in-view: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SQLServerDialect
#        format_sql: true
#
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
#          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
#          
#oauth:
#  url: http://localhost:9103/oauth          
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always          
#          
#logging:
#  level:
#    com.hpy: debug
#    root: INFO
#  file:
#    name: D:/var/logs/application.log  
##    name: .var/log/applicaltion.log
#
#    
#
#synergy:
#  base-url: https://ops360uat.hitachi-payments.com/ops/synergy/HitachiAPI_IntegrationUAT/api
#  username: OPS360API
#  password: Cogent@123
#  
#
#jwt:
#  auth:
#    converter:
#      resource-id: ${keycloak.resource}
#      principle-attribute: preferred_username  
#
#keycloak:
#  domain: localhost:8080
#  realm: HPY
#  resource: ops-360
#  issuer-uri: http://${keycloak.domain}
#  adminClientSecret: 3Asf42GnEqOfatIQZULao5764AoYNnLY
#
#  auth-server-url: http://${keycloak.domain}
#  adminClientId: ${keycloak.resource}
#  urls:
#    auth: http://${keycloak.domain}
#    tokenURL: http://${keycloak.domain}/realms/${keycloak.realm}/protocol/openid-connect/token
#  ssl-required: external
#  use-resource-role-mappings: true  
#
#app:
#  documentUploadDirectory: D:\\documentDirectory
#  maxFileSize: 2097152
#  cross-origin:
#    allow: https://ops360uat.hitachi-payments.com
#  
#eureka:
#  instance:
#    prerfer-ip-address: true
#  client:
#    fetch-registry: true
#    registry-with-eureka: true
#    service-url:
#      defaultZone: http://127.0.0.1:9101/eureka
#
#    
#
#
#
#
#
