server:
  port: 9204

spring:
  boot:
    admin:
      client:
        url: http://172.16.24.58:9000 #Admin portal url.
        instance:
          name: Synergy Service
          service-base-url: http://172.16.24.57:9098 #This is current application url.
  application:
    name: prompt-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

#  datasource:
#    url: jdbc:postgresql://localhost:5432/test
#    username: postgres
#    password: Hitachi@123
#    driver-class-name: org.postgresql.Driver
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      show-sql: true
#      format_sql: true
  datasource:
    url: jdbc:sqlserver://172.16.24.64:1433;databaseName=OPS360;encrypt=true;trustServerCertificate=true;
    username: ops.production
    password: pro@ops360
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

jwt:
  auth:
    converter:
      resource-id: ${keycloak.resource}
      principle-attribute: preferred_username

keycloak:
#  domain: ops360dev.hitachi-payments.com:9102
  domain: 172.16.24.58:9102
  realm: HPY
  resource: ops360
  issuer-uri: http://${keycloak.domain}
  adminClientSecret: 3Asf42GnEqOfatIQZULao5764AoYNnLY
  auth-server-url: http://${keycloak.domain}
  adminClientId: ${keycloak.resource}
  urls:
    auth: http://${keycloak.domain}
    tokenURL: http://${keycloak.domain}/realms/${keycloak.realm}/protocol/openid-connect/token
  ssl-required: external
  use-resource-role-mappings: true 
  
eureka:
  instance:
    prerfer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://172.16.24.58:9101/eureka
      
      
app:
  cross-origin:
    allow: https://ops360.hitachi-payments.com