Server:
  port: 9203

springdoc:
 api-docs:
   path: /v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
 swagger-ui:
   path: /swagger-ui.html

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      properties:
        max.in.flight.requests.per.connection: 1
        enable.idempotence: true
  aop:
    proxy-target-class: false
    auto: true
  boot:
    admin:
      client:
        url: http://localhost:8000 #Admin portal url.
        instance:
          name: ATM Service
          service-base-url: http://localhost:9203 #This is current application url.
  application:
    name: atm-service
  datasource:
    url: jdbc:sqlserver://172.16.15.120:1433;databaseName=OPS360;encrypt=true;trustServerCertificate=true;
    username: appuser
    password: hitachi@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
     naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

synergy:
  base-url: https://ops360dev.hitachi-payments.com/synergy/HitachiAPI_Integration/api
  username: OPS360API
  password: Cogent@123
  
app:
  cross-origin:
    allow: https://ops360uat.hitachi-payments.com

jwt:
  auth:
    converter:
      resource-id: ${keycloak.resource}
      principle-attribute: preferred_username  

keycloak:
  domain: localhost:8080
#  domain: 172.16.15.192:9102
#  domain: ops360dev.hitachi-payments.com:9102
  realm: HPY
  resource: ops-360
  issuer-uri: http://${keycloak.domain}
  adminClientSecret: 13ptMbHcKqskC5zC586keD7VNBGsUTkJ
  auth-server-url: http://${keycloak.domain}
  adminClientId: ${keycloak.resource}
  urls:
    auth: http://${keycloak.domain}
    tokenURL: http://${keycloak.domain}/realms/${keycloak.realm}/protocol/openid-connect/token
  ssl-required: external
  use-resource-role-mappings: true  
  
ops360:
  dashboard:
    max-atm-list-count: 5

#app:
#  documentUploadDirectory: D:\\documentDirectory
#  maxFileSize: 2097152
  
eureka:
  instance:
    prerfer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
#      defaultZone: http://172.16.15.192:9101/eureka
      defaultZone: http://127.0.0.1:9101/eureka
   

