Server:
  port: 9202

spring:
  web:
    resources:
      static-locations: file:/usr/ops360/Asset/
      add-mappings: true
  boot:
    admin:
      client:
         url: http://172.16.15.192:9000 #Admin portal url.
         instance:
           name: Ticketing Service
           service-base-url: http://172.16.15.191:9202 #This is current application url.
  application:
    name: ticketing
  
  datasource:
    url: jdbc:sqlserver://172.16.15.120:1433;databaseName=OPS360UAT;encrypt=true;trustServerCertificate=true;
    username: appuser
    password: hitachi@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:172.16.15.196:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      properties:
        max.in.flight.requests.per.connection: 1
        enable.idempotence: true    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


synergy:
  base-url: https://ops360dev.hitachi-payments.com/synergy/HitachiAPI_Integration/api
  username: OPS360API
  password: Cogent@123

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  

jwt:
  auth:
    converter:
      resource-id: ${keycloak.resource}
      principle-attribute: preferred_username  


keycloak:
  domain: 172.16.15.192:9102
  realm: HPY
  resource: ops360
  issuer-uri: http://${keycloak.domain}
  adminClientSecret: 3Asf42GnEqOfatIQZULao5764AoYNnLY
  auth-server-url: http://${keycloak.domain}
  adminClientId: ${keycloak.resource}
  urls:
    auth: http://${keycloak.domain}
    tokenURL: http://${keycloak.domain}/realms/${keycloak.realm}/protocol/openid-connect/token
  ssl-required: external
  use-resource-role-mappings: true  

app:
  documentUploadDirectory: D:\\documentDirectory
  maxFileSize: 2097152
  cross-origin:
    allow: https://ops360uat.hitachi-payments.com
  
eureka:
  instance:
    prerfer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://172.16.15.192:9101/eureka

ops360:
  assets:
    base-path: /usr/ops360/Assets/ticket-archival/
    base-url: https://ops360uat.hitachi-payments.com/ticketarchive/
  ticketing:
    max-atm-list-count: 5
    atm-batch-size: 50
    
knowlarity-service:
       url: http://172.16.15.192:9207/knowlarity
uam-service:
       url:  http://172.16.15.192:9100/user-service

dashboard-service:
       url: http://172.16.15.192:9200/Cm_portalATMDetails	

synergy-service:
       url: http://172.16.15.192:9206/synergy
oauth-service:
       url: http://172.16.15.192:9103/oauth
       
hims:
  api:
    base:
      #url: "https://7c18b3a9-3608-415b-b7d6-fb6a3942c1db.mock.pstmn.io"
      #url: "https://172.16.15.36:9456/api"
      url: "https://hims-crm.hitachi-payments.com:9456/api"
    update:
      endpoint: "/Update_FollowUp_Details"
    create:
      endpoint: "/Create_Service_Ticket"
    enabled: true
    timeout: 5000
    retry:
      attempts: 3
      